config/routes.rb
Web::Application.routes.draw do
  scope ENV['RAILS_RELATIVE_URL_ROOT'] || '/' do 
    
    namespace :admin do
      resources :markets do
        resources :jobs
      end
      resources :users do
        collection do
          get :search
          get :search_self
        end
      end 
      resources :services
      resources :proxy_uploads
      resources :proxies do
        collection do
          get :import
        end
      end
    end
    match :admin, :via => [:get], to: 'pages#admin'

    namespace :client do
      [:edit_preferences, :update_preferences, :change_password, :update_password].each do |action|
        match action, :via => [:get], to: "pages##{action}"
      end
      
      resources :markets do   
        resources :uploads do
          collection do
            get :template          
          end
          member do
            get :activate_tab, :export , :comps_report 
          end
        end    
        resources :properties do
          collection do 
            get :comps_rental_export,:comps_sale_export,:comps_build_export,:saved,:set_per_page,:opportunities,:search_opportunities
            post :rem_myprop
          end
          member do 
            get :summary,:client_sale_data_set_per_page,:client_rental_data_set_per_page,:comps_rental,:comps_sale,:comps_build,
            :map,:comment,:add_saved, :remove_saved, :capex_calc, :request_visit, :request_visit_form, :neighborhood, :show_rental_comps, :show_rental_comps_qualified, :show_rental_comps_others, :show_sale_comps_qualified, :show_sale_comps_others, :show_sale_comps, :show_subject_property
            post :recompute,:save,:update_flood,:update_tag,:update_near_commercial,:update_rep,:save_comment,:schedule_visit         
          end
        end
        resources :searches do
          member do
            get :map, :export, :set_per_page
            post :add_my_prop, :add_label
          end
        end
      end
      
    end
    match :client, :via => [:get], to: 'pages#client'

    resources :markets do 
      scope :module => :markets do
        resources :searches do
          member do
            get :map, :export, :set_per_page
            post :add_my_prop, :add_label
          end
        end
        resources :uploads do
          collection do
            get :template          
          end
          member do
            get :activate_tab, :export , :comps_report 
          end
        end
        resources :properties do 
          collection do
            get :saved, :export, :set_per_page, :comps_sale_export, :comps_rental_export, :comps_build_export
            post :rem_myprop
          end
          member do 
            get :summary, :add_saved, :remove_saved, :map, :comps_rental, :comps_sale, :comps_build, :proforma, :raw, :level2, :level3, :comment, :data_set_per_page
            post :save_proforma, :recompute, :save_comment, :update_rep, :update_tag, :update_flood, :update_near_commercial
          end
        end
      end
    end

    #resources :users

    devise_for :users

    [:edit_preferences, :update_preferences, :change_password, :update_password].each do |action|
      match action, :via => [:get], to: "pages##{action}"
    end

    # root :to => "pages#welcome"
    # root 'home#index'
    # get ':path', to: 'home#index', format: false
    match '*path', :via => [:get], :to => "application#not_found"
  end

end

app/controllers/admin/markets_controller.rb
class Admin::MarketsController < Admin::BaseController
  acts_as_resource do
    actions :all, except: [:show]
  end
  
  def update
     @market.assign_attributes(params[:market])
     if params[:confirm]
       perform_update
     else       
       if !@market.assumptions_changed?
         perform_update
       else
         flash.now[:warning] = 'With assumptions changed, you will need to recomputes all properties in this market.<br> Are you sure you want to continue saving changes?'.html_safe
         render 'edit'
       end
     end
     
     
    
  end
  
  # def update
    # update! do
#       
      # collection_url
#       
    # end
    # if @market.save?
      # edit_resource_url(@market)
    # else
      # collection_url
    # end
     
    
    # if @market.assumption_changed?
      # edit_resource_url(@market)
    # else
      # update!
      # collection_url
    # end
    
    # puts "market rental_comp_query: #{@market.rental_comp_query}"
    # puts "market rental_comp_query changed?: #{@market.rental_comp_query_changed?}"
#     
    # rental_comp_query = @market.rental_comp_query
#     
    # update! do
      # puts "market rental_comp comparison: #{rental_comp_query} vs  #{@market.rental_comp_query}"
      # if rental_comp_query !=  @market.rental_comp_query
        # edit_resource_url(@market)
      # else 
        # # @market.save
        # collection_url
      # end
    # end
    # @market = Market.new(params[:market])
    # update!
    # if @market.assumption_changed?
      # puts "aaaa"
      # redirect_to "http://www.google.co.th"
      # # redirect_to edit_resource_url(:market => params[:market] )
    # else
      # redirect_to collection_url
    # end
  # end
  
  protected

    def collection
      @markets = Market.includes(:users).page(params[:page])
    end
    
    def perform_update
      if @market.save
        redirect_to url_for(:action => :index), :notice => 'Settings saved successfully!'
      else
        flash.now[:error] = 'Settings could not be saved, check errors!'
        render 'edit'
      end
    end

end

app/controllers/client/markets_controller.rb
class Client::MarketsController < Client::BaseController
  before_filter proc { load_market_and_assignment(:id) }
  acts_as_resource do
    actions :all, except: [:show]
  end
  
  def show
    if can? :create, Search
      redirect_to new_client_market_search_url(@market)
    elsif can? :create, Job
      redirect_to new_client_market_upload_url(@market)
    end
  end
  
  def update
    
     if params[:restore]
      @assignment.restore!
      redirect_to url_for(:action => :edit), :notice => 'Settings restored successfully from market default values!'
    else
      if @assignment.update_attributes(params[:market_assignment])
        redirect_to url_for(:action => :edit), :notice => 'Settings saved successfully!'
      else
        flash.now[:error] = 'Settings could not be saved, check errors!'
        render 'edit'
      end
    end
     # @market.assign_attributes(params[:market])
     # if params[:confirm]
       # perform_update
     # else       
       # if !@market.assumptions_changed?
         # perform_update
       # else
         # flash.now[:warning] = 'With assumptions changed, you will need to recomputes all properties in this market.<br> Are you sure you want to continue saving changes?'.html_safe
         # render 'edit'
       # end
     # end
     
     
    
  end
  
  # def update
    # update! do
#       
      # collection_url
#       
    # end
    # if @market.save?
      # edit_resource_url(@market)
    # else
      # collection_url
    # end
     
    
    # if @market.assumption_changed?
      # edit_resource_url(@market)
    # else
      # update!
      # collection_url
    # end
    
    # puts "market rental_comp_query: #{@market.rental_comp_query}"
    # puts "market rental_comp_query changed?: #{@market.rental_comp_query_changed?}"
#     
    # rental_comp_query = @market.rental_comp_query
#     
    # update! do
      # puts "market rental_comp comparison: #{rental_comp_query} vs  #{@market.rental_comp_query}"
      # if rental_comp_query !=  @market.rental_comp_query
        # edit_resource_url(@market)
      # else 
        # # @market.save
        # collection_url
      # end
    # end
    # @market = Market.new(params[:market])
    # update!
    # if @market.assumption_changed?
      # puts "aaaa"
      # redirect_to "http://www.google.co.th"
      # # redirect_to edit_resource_url(:market => params[:market] )
    # else
      # redirect_to collection_url
    # end
  # end
  
  protected

    def collection
      @markets = Market.includes(:users).page(params[:page])
    end
    
    def perform_update
      
      m  = @market.save
      Delayed::Worker.logger.debug "m: #{@market.errors.full_messages}"
      if m
        redirect_to url_for(:action => :index), :notice => 'Settings saved successfully fu!'
      else
        flash.now[:error] = 'Settings could not be saved, check errors!'
        render 'edit'
      end
    end

end

app/controllers/client/uploads_controller.rb
class Client::UploadsController < Client::BaseController
  before_filter :load_market_and_assignment
  before_filter :prepare_job, only: [:new, :create]

  acts_as_resource(Job) do    
    defaults route_prefix: :client
    belongs_to :market
    custom_actions collection: [:template], resource: [:export,:comps_report]
  end
  
  def new
    session.delete(:selected_tab)
    new!
  end
  
  def index
    @reload = 30000
    index!
  end

  def destroy
    resource.delete
    redirect_to collection_url
  end

  def template
    download(:csv, 'template', Property.limit(0).to_csv(Property::IMPORT_FIELDS))
  end
  
  def activate_tab
    session[:selected_tab] =   params[:selected_tab]
    render :nothing => true
  end

  def show
    ids = (resource.info[:ids] || '').split(' ')
    @properties = @market.properties.joins_proforma.where(id: ids).page(params[:page]).order_by(sort_by, sort_asc)
  end

  def create
    @upload.assign_attributes(params[:market_upload_job])
    create!
  end
  
  def export
    ids = (resource.info[:ids] || '').split(' ')
    properties = @market.properties.joins_proforma.where(id: ids)
    download(:csv, 'report', properties.to_csv4(current_user.preferences.columns_results))
  end
  
  def comps_report
    ids = (resource.info[:ids] || '').split(' ')
    properties = @market.properties.joins_proforma.where(id: ids)
    download(:csv, 'comps_report', properties.to_comps_report(Property::COMPS_REPORT_FIELDS))
  end
  
  

  private

    def prepare_job 
      @upload = MarketUploadJob.new(market_id: @market.try(:id), user_id: current_user_id)
      @upload.overrides = Array.new(3, {}) if can?(:bulk, Job)
    end

    def collection
      @uploads = @market.uploads.where(user_id: current_user_id).page(params[:page]).desc(:run_at)
    end

end

app/controllers/markets/base_controller.rb
class Markets::BaseController < ApplicationController
  before_filter :load_market_and_assignment

end

app/controllers/markets/uploads_controller.rb
class Markets::UploadsController < Markets::BaseController
  before_filter :prepare_job, only: [:new, :create]

  acts_as_resource(Job) do 
    defaults route_prefix: nil
    belongs_to :market
    custom_actions collection: [:template], resource: [:export,:comps_report]
  end
  
  def new
    session.delete(:selected_tab)
    new!
  end
  
  def index
    @reload = 30000
    index!
  end

  def destroy
    resource.delete
    redirect_to collection_url
  end

  def template
    download(:csv, 'template', Property.limit(0).to_csv(Property::IMPORT_FIELDS))
  end
  
  def activate_tab
    session[:selected_tab] =   params[:selected_tab]
    render :nothing => true
  end

  def show
    ids = (resource.info[:ids] || '').split(' ')
    @properties = @market.properties.joins_proforma.where(id: ids).page(params[:page]).order_by(sort_by, sort_asc)
  end

  def create
    @upload.assign_attributes(params[:market_upload_job])
    create!
  end
  
  def export
    ids = (resource.info[:ids] || '').split(' ')
    properties = @market.properties.joins_proforma.where(id: ids)
    download(:csv, 'report', properties.to_csv4(current_user.preferences.columns_results))
  end
  
  def comps_report
    ids = (resource.info[:ids] || '').split(' ')
    properties = @market.properties.joins_proforma.where(id: ids)
    download(:csv, 'comps_report', properties.to_comps_report(Property::COMPS_REPORT_FIELDS))
  end
  
  

  private

    def prepare_job 
      @upload = MarketUploadJob.new(market_id: @market.try(:id), user_id: current_user_id)
      @upload.overrides = Array.new(3, {}) if can?(:bulk, Job)
    end

    def collection
      @uploads = @market.uploads.where(user_id: current_user_id).page(params[:page]).desc(:run_at)
    end

end

app/controllers/markets_controller.rb
class MarketsController < ApplicationController
  before_filter proc { load_market_and_assignment(:id) }
  acts_as_resource

  def show
    if can? :create, Search
      redirect_to new_market_search_url(@market)
    elsif can? :create, Job
      redirect_to new_market_upload_url(@market)
    end
  end

  def update
    if params[:restore]
      @assignment.restore!
      redirect_to url_for(:action => :edit), :notice => 'Settings restored successfully from market default values!'
    else
      if @assignment.update_attributes(params[:market_assignment])
        redirect_to url_for(:action => :edit), :notice => 'Settings saved successfully!'
      else
        flash.now[:error] = 'Settings could not be saved, check errors!'
        render 'edit'
      end
    end
  end

end

app/views/markets/uploads/_form.html.haml
%p= t(:description)
= simple_form_for(@upload, url: market_uploads_url(@market)) do |f|
  - if can? :bulk, Job
    .well
      %h5.inline= t(:upload_entry)         
    =f.input :source, hint: t(:source_hint)
    =f.input :files, as: :file, label: t(:files_label), hint: link_to(t(:download_template), template_market_uploads_url(@market)), input_html: { accept: 'text/csv' }
  
  .well
    %h5.inline= t(:manual_entry)
    - if can? :bulk, Job
      .pull-right
        =link_to t(:add_row), '#', class: 'add_fields', 'data-association-insertion-method' => :prepend, 'data-association-insertion-node' => 'tbody.overrides', 'data-association-insertion-template' => "#{render('override', f: f, object: {})}"
  .row
    .span12.xscroll
      %table.table.table-hover
        %thead
          %tr
            &nbsp; You are required to enter some combination of the following fields. MLS # or TAX # & Zip or Tax # & County or Address & Zip or Address & County. Other fields are optional.
            %th 
            - for attr in Property::IMPORT_FIELDS
              - if (['tax_id', 'street_address', 'zip_code', 'county'].include? attr)
                %th= "#{Property.label(attr, :short)}*"  
              - elsif (['list_price'].include? attr)
                %th= "#{Property.label(attr)}"         
              - else
                %th= Property.label(attr, :short)
        %tbody.overrides
          - for override in @upload.overrides
            =render 'override', f: f, object: override
  
  .controlbar
    .container
      .form-actions
        =f.button :submit, t('.submit'), :disable_with => t('wait')
        =link_to t(:cancel), collection_url, class: 'btn btn-link'

app/views/markets/uploads/_override.html.haml
= f.fields_for :overrides, object: object, index: '' do |d|
  %tr
    %td= link_to t(:delete), '#', data: {toggle: :delete}
    - for attr in Property::IMPORT_FIELDS
      %td= d.input attr, label: false, model: Property, input_html: {class: 'input-small', value: object[attr]}, unchecked_value: nil

app/views/markets/uploads/edit.html.haml
=render :partial => 'form'

app/views/markets/uploads/index.html.haml
= page_info(@uploads)
%table.table.table-hover
  %thead
    - for attr in [:run_at, :user, :started_at, :completed_at, :status, :results_count, :errors_count]
      %th= Job.label(attr)
    %th= t(:actions)
  %tbody
    - for upload in @uploads
      %tr
        %td= upload.format(:run_at)
        %td= upload.format(:user)
        %td= upload.format(:started_at, as: :time)
        %td= upload.format(:completed_at, as: :time)
        %td= upload.format(:status)
        %td= upload.format(:results_count)
        %td= upload.format(:errors_count)
        %td.nowrap
          %ul.nav.nav-links
            - if can? :show, upload
              =nav_item t(:show), market_upload_url(@market, upload)
            - if can? :destroy, upload
              =nav_item t(:delete), resource_url(upload), :method => :delete, :confirm => t(:are_you_sure)

app/views/markets/uploads/new.html.haml
=render :partial => 'form'

app/views/markets/uploads/show.html.haml
.tabbable
  %ul.nav.nav-tabs
    - for key in [(:error if @upload.status == 'error'), :results, :info].compact
      =tab_item t(key), "##{key}"
  .tab-content
    .tab-pane#error
      =debug(@upload.last_error, true)
    .tab-pane#results
      = render 'properties', data: @properties, columns: current_user.preferences.columns_results
    .tab-pane#info
      =debug(@upload.info, true)