config/routes.rb
Web::Application.routes.draw do
  scope ENV['RAILS_RELATIVE_URL_ROOT'] || '/' do 
    
    namespace :admin do
      resources :markets do
        resources :jobs
      end
      resources :users do
        collection do
          get :search
          get :search_self
        end
      end 
      resources :services
      resources :proxy_uploads
      resources :proxies do
        collection do
          get :import
        end
      end
    end
    match :admin, :via => [:get], to: 'pages#admin'

    namespace :client do
      [:edit_preferences, :update_preferences, :change_password, :update_password].each do |action|
        match action, :via => [:get], to: "pages##{action}"
      end
      
      resources :markets do   
        resources :uploads do
          collection do
            get :template          
          end
          member do
            get :activate_tab, :export , :comps_report 
          end
        end    
        resources :properties do
          collection do 
            get :comps_rental_export,:comps_sale_export,:comps_build_export,:saved,:set_per_page,:opportunities,:search_opportunities
            post :rem_myprop
          end
          member do 
            get :summary,:client_sale_data_set_per_page,:client_rental_data_set_per_page,:comps_rental,:comps_sale,:comps_build,
            :map,:comment,:add_saved, :remove_saved, :capex_calc, :request_visit, :request_visit_form, :neighborhood, :show_rental_comps, :show_rental_comps_qualified, :show_rental_comps_others, :show_sale_comps_qualified, :show_sale_comps_others, :show_sale_comps, :show_subject_property
            post :recompute,:save,:update_flood,:update_tag,:update_near_commercial,:update_rep,:save_comment,:schedule_visit         
          end
        end
        resources :searches do
          member do
            get :map, :export, :set_per_page
            post :add_my_prop, :add_label
          end
        end
      end
      
    end
    match :client, :via => [:get], to: 'pages#client'

    resources :markets do 
      scope :module => :markets do
        resources :searches do
          member do
            get :map, :export, :set_per_page
            post :add_my_prop, :add_label
          end
        end
        resources :uploads do
          collection do
            get :template          
          end
          member do
            get :activate_tab, :export , :comps_report 
          end
        end
        resources :properties do 
          collection do
            get :saved, :export, :set_per_page, :comps_sale_export, :comps_rental_export, :comps_build_export
            post :rem_myprop
          end
          member do 
            get :summary, :add_saved, :remove_saved, :map, :comps_rental, :comps_sale, :comps_build, :proforma, :raw, :level2, :level3, :comment, :data_set_per_page
            post :save_proforma, :recompute, :save_comment, :update_rep, :update_tag, :update_flood, :update_near_commercial
          end
        end
      end
    end

    #resources :users

    devise_for :users

    [:edit_preferences, :update_preferences, :change_password, :update_password].each do |action|
      match action, :via => [:get], to: "pages##{action}"
    end

    # root :to => "pages#welcome"
    # root 'home#index'
    # get ':path', to: 'home#index', format: false
    match '*path', :via => [:get], :to => "application#not_found"
  end

end

app/models/job.rb
class Job < ActiveRecord::Base 
  include Delayed::Backend::Base

  self.per_page = 20

  attr_config do |c|
    # c._delegate JobDetail, :detail
    # delayed_jobs default columns
    c.priority integer: 0                     # Allows some jobs to jump to the front of the queue
    c.attempts integer: 0                     # Provides for retries, but still fail eventually.
    c.handler :text                           # YAML-encoded string of the object that will do work
    c.last_error :text                        # reason for last failure (See Note below)
    c.run_at :datetime                        # When to run. Could be Time.zone.now for immediately, or sometime in the future.
    c.locked_at :datetime                     # Set when a client is working on this object
    c.failed_at :datetime                     # Set when all retries have failed (actually, by default, the record is deleted instead)
    c.locked_by :string                       # Who is working on this object (if locked)
    c.queue :string                           # The name of the queue this job is in
    # custom columns
    c.started_at :datetime
    c.completed_at :datetime
    c.results_count :integer
    c.errors_count :integer
    c.status :enum, in: %w{error success pending running}
    c.name :string
    c.info :serialize
  end

  belongs_to :market
  belongs_to :user

  before_save :set_default_run_at

  # Delayed::Backend::ActiveRecord::Job overrides

  def handler_hash
    YAML.load(self.handler)
  end

  def running?
    self.status == 'running'
  end

  def destroy
    # do not destroy
  end

  def self.ready_to_run(worker_name, max_run_time)
    where('completed_at IS NULL && (run_at <= ? AND (locked_at IS NULL OR locked_at < ?) OR locked_by = ?) AND failed_at IS NULL', db_time_now, db_time_now - max_run_time, worker_name)
  end
  
  def invoke_job
    Delayed::Worker.lifecycle.run_callbacks(:invoke_job, self) do
      begin
        hook :before
        update_attributes!(status: 'running', started_at: Job.db_time_now)
        payload_object.perform
        Delayed::Worker.logger.debug "~~job name:#{name}"
        hook :success
        
        if name != 'MarketComputeJob'
          update_attributes!(status: 'success', completed_at: Job.db_time_now)
        else
          update_attributes!(status: 'running', completed_at: Job.db_time_now, results_count: nil, errors_count: nil)
        end
        
      rescue Exception => e
        hook :error, e
        update_attributes!(status: 'error', completed_at: Job.db_time_now)
        raise e
      ensure
        hook :after
        save!
      end
    end
  end

  # Delayed::Backend::ActiveRecord::Job implementation
  def self.by_priority
    order('priority ASC, run_at ASC')
  end

  def self.before_fork
    ::ActiveRecord::Base.clear_all_connections!
  end

  def self.after_fork
    ::ActiveRecord::Base.establish_connection
  end

  # When a worker is exiting, make sure we don't have any locked jobs.
  def self.clear_locks!(worker_name)
    update_all("locked_by = null, locked_at = null", ["locked_by = ?", worker_name])
  end

  # Find a few candidate jobs to run (in case some immediately get locked by others).
  def self.find_available(worker_name, limit = 5, max_run_time = Delayed::Worker.max_run_time)
    scope = self.ready_to_run(worker_name, max_run_time)
    scope = scope.scoped(:conditions => ['priority >= ?', Delayed::Worker.min_priority]) if Delayed::Worker.min_priority
    scope = scope.scoped(:conditions => ['priority <= ?', Delayed::Worker.max_priority]) if Delayed::Worker.max_priority
    scope = scope.scoped(:conditions => ["queue IN (?)", Delayed::Worker.queues]) if Delayed::Worker.queues.any?

    silence do
      scope.by_priority.all(:limit => limit)
    end
    # nil
  end

  # Lock this job for this worker.
  # Returns true if we have the lock, false otherwise.
  def lock_exclusively!(max_run_time, worker)
    now = self.class.db_time_now
    affected_rows = if locked_by != worker
      # We don't own this job so we will update the locked_by name and the locked_at
      self.class.update_all(["locked_at = ?, locked_by = ?", now, worker], ["id = ? and (locked_at is null or locked_at < ?) and (run_at <= ?)", id, (now - max_run_time.to_i), now])
    else
      # We already own this job, this may happen if the job queue crashes.
      # Simply resume and update the locked_at
      self.class.update_all(["locked_at = ?", now], ["id = ? and locked_by = ?", id, worker])
    end
    if affected_rows == 1
      self.locked_at = now
      self.locked_by = worker
      self.changed_attributes.clear
      return true
    else
      return false
    end
  end

  # Get the current time (GMT or local depending on DB)
  # Note: This does not ping the DB to get the time, so all your clients
  # must have syncronized clocks.
  def self.db_time_now
    if Time.zone
      Time.zone.now
    elsif ::ActiveRecord::Base.default_timezone == :utc
      Time.now.utc
    else
      Time.now
    end
  end

  def reload(*args)
    reset
    super
  end
end

app/controllers/admin/jobs_controller.rb
class Admin::JobsController < Admin::BaseController
  before_filter :load_market_and_assignment
  before_filter :load_job_types, only: [:new, :create]

  acts_as_resource(Job) do 
    defaults route_prefix: :admin
    belongs_to :market
    actions :all, except: [:edit, :update]
  end

  def create
    config = params[:market_job]
    type = config.delete(:type)
    @job = case type
      when 'import' then @import
      when 'grab' then @grab
      when 'compute' then @compute
      when 'email' then @email
    end
    @job.assign_attributes(config)
    create!
  end

  def index
    @reload = 30000
    index!
  end

  def destroy
    destroy! do
      @job.delete
      collection_url
    end
  end

  protected

    def collection
      @jobs = @market.jobs.page(params[:page]).desc(:run_at)
    end

    def load_job_types
      @import = MarketImportJob.new(market_id: @market.id)
      @grab = MarketGrabJob.new(market_id: @market.id)
      @compute = MarketComputeJob.new(market_id: @market.id)
      @email = MarketEmailJob.new(market_id: @market.id)
    end
end

app/views/admin/jobs/index.html.haml
= page_info(@jobs)
%table.table.table-hover
  %thead
    - for attr in [:run_at, :name, :user, :started_at, :completed_at, :status, :priority, :results_count, :errors_count]
      %th= Job.label(attr)
    %th= t(:actions)
  %tbody
    - for job in @jobs
      %tr
        %td= job.format(:run_at)
        %td= job.format(:name)
        %td= job.format(:user)
        %td= job.format(:started_at, as: :time)
        %td= job.format(:completed_at, as: :time)
        %td= job.format(:status)
        %td= job.format(:priority)
        %td= job.format(:results_count)
        %td= job.format(:errors_count)
        %td.nowrap
          %ul.nav.nav-links
            - if can? :show, job
              =nav_item t(:show), resource_url(job)
            - if can? :destroy, job
              =nav_item t(:delete), resource_url(job), :method => :delete, :confirm => t(:are_you_sure)

app/views/admin/jobs/new.html.haml
.row
  .span3
    %h5= t(:import)
    = simple_form_for(@import, as: :market_job, url: admin_market_jobs_url(@market), observe: true, direction: :vertical) do |f|
      =f.hidden_field :type, value: 'import'
      =f.input :files, as: :file, input_html: {multiple: true}
      .form-actions
        =f.submit t(:submit), disable_with: t('wait'), class: 'btn btn-primary'
  .span3
    %h5= t(:grab)
    = simple_form_for(@grab, as: :market_job, url: admin_market_jobs_url(@market), observe: true, direction: :vertical) do |f|
      =f.hidden_field :type, value: 'grab'
      - unless @market.id.in?([2,3,4,5,6])
        =f.input :days, as: :integer
      .form-actions
        =f.submit t(:submit), disable_with: t('wait'), class: 'btn btn-primary'
  .span3
    %h5= t(:compute)
    = simple_form_for(@compute, as: :market_job, url: admin_market_jobs_url(@market), observe: true, direction: :vertical) do |f|
      =f.hidden_field :type, value: 'compute'
      =f.input :active_pending, as: :boolean, unchecked_value: nil, label: false, inline_label: 'Active/Pending'
      =f.input :not_active_pending, as: :boolean, unchecked_value: nil, label: false, inline_label: 'Others'    
      =f.input :rental_type, as: :boolean, unchecked_value: nil, label: false, inline_label: 'Rental'      
      =f.input :limit, as: :integer
      =f.input :force, as: :boolean, label: false, inline_label: true, unchecked_value: nil
      =f.input :general_start_id, as: :string, label: '#GLT ID from', input_html: {class: 'general_id_togglible'}
      =f.input :general_end_id, as: :string, label: 'to', input_html: {class: 'general_id_togglible'}
      =f.input :duration , as: :boolean, label: false, inline_label: true, unchecked_value: nil
      =f.input :general_start_date, as: :date, label: 'Date Updated from', input_html: {class: 'general_date_togglible'}
      =f.input :general_end_date, as: :date, label: 'to', input_html: {class: 'general_date_togglible'}
      .form-hr
      =f.input :active, as: :boolean, unchecked_value: nil, label: false, inline_label: 'Active & Not Computed'
      =f.input :active_start_id, as: :string, label: '#GLT ID from', input_html: {class: 'active_id_togglible'}
      =f.input :active_end_id, as: :string, label: 'to', input_html: {class: 'active_id_togglible'}
      .form-hr
      =f.input :missing_zillows, as: :boolean, unchecked_value: nil, label: false, inline_label: 'Missing Zillows'
      =f.input :active_single_family, as: :boolean, unchecked_value: nil, label: false, inline_label: 'Active Single Family'
      =f.input :custom_ids, as: :string, label: 'ids'
      .form-actions
        =f.submit t(:submit), disable_with: t('wait'), class: 'btn btn-primary'
  .span3
    %h5= t(:email)
    = simple_form_for(@email, as: :market_job, url: admin_market_jobs_url(@market), observe: true, direction: :vertical) do |f|
      =f.hidden_field :type, value: 'import'
      .form-actions
        =f.submit t(:submit), disable_with: t('wait'), class: 'btn btn-primary'
    

app/views/admin/jobs/show.html.haml
.tabbable
  %ul.nav.nav-tabs
    - for key in [(:error if @job.status == 'error'), :info, :config].compact
      =tab_item t(key), "##{key}"
  .tab-content
    .tab-pane#error
      =debug(@job.last_error, true)
    .tab-pane#config
      =debug(YAML.load(@job.handler), true)
    .tab-pane#info
      =debug(@job.info, true)
    