config/routes.rb
Web::Application.routes.draw do
  scope ENV['RAILS_RELATIVE_URL_ROOT'] || '/' do 
    
    namespace :admin do
      resources :markets do
        resources :jobs
      end
      resources :users do
        collection do
          get :search
          get :search_self
        end
      end 
      resources :services
      resources :proxy_uploads
      resources :proxies do
        collection do
          get :import
        end
      end
    end
    match :admin, :via => [:get], to: 'pages#admin'

    namespace :client do
      [:edit_preferences, :update_preferences, :change_password, :update_password].each do |action|
        match action, :via => [:get], to: "pages##{action}"
      end
      
      resources :markets do   
        resources :uploads do
          collection do
            get :template          
          end
          member do
            get :activate_tab, :export , :comps_report 
          end
        end    
        resources :properties do
          collection do 
            get :comps_rental_export,:comps_sale_export,:comps_build_export,:saved,:set_per_page,:opportunities,:search_opportunities
            post :rem_myprop
          end
          member do 
            get :summary,:client_sale_data_set_per_page,:client_rental_data_set_per_page,:comps_rental,:comps_sale,:comps_build,
            :map,:comment,:add_saved, :remove_saved, :capex_calc, :request_visit, :request_visit_form, :neighborhood, :show_rental_comps, :show_rental_comps_qualified, :show_rental_comps_others, :show_sale_comps_qualified, :show_sale_comps_others, :show_sale_comps, :show_subject_property
            post :recompute,:save,:update_flood,:update_tag,:update_near_commercial,:update_rep,:save_comment,:schedule_visit         
          end
        end
        resources :searches do
          member do
            get :map, :export, :set_per_page
            post :add_my_prop, :add_label
          end
        end
      end
      
    end
    match :client, :via => [:get], to: 'pages#client'

    resources :markets do 
      scope :module => :markets do
        resources :searches do
          member do
            get :map, :export, :set_per_page
            post :add_my_prop, :add_label
          end
        end
        resources :uploads do
          collection do
            get :template          
          end
          member do
            get :activate_tab, :export , :comps_report 
          end
        end
        resources :properties do 
          collection do
            get :saved, :export, :set_per_page, :comps_sale_export, :comps_rental_export, :comps_build_export
            post :rem_myprop
          end
          member do 
            get :summary, :add_saved, :remove_saved, :map, :comps_rental, :comps_sale, :comps_build, :proforma, :raw, :level2, :level3, :comment, :data_set_per_page
            post :save_proforma, :recompute, :save_comment, :update_rep, :update_tag, :update_flood, :update_near_commercial
          end
        end
      end
    end

    #resources :users

    devise_for :users

    [:edit_preferences, :update_preferences, :change_password, :update_password].each do |action|
      match action, :via => [:get], to: "pages##{action}"
    end

    # root :to => "pages#welcome"
    # root 'home#index'
    # get ':path', to: 'home#index', format: false
    match '*path', :via => [:get], :to => "application#not_found"
  end

end

app/controllers/admin/markets_controller.rb
class Admin::MarketsController < Admin::BaseController
  acts_as_resource do
    actions :all, except: [:show]
  end
  
  def update
     @market.assign_attributes(params[:market])
     if params[:confirm]
       perform_update
     else       
       if !@market.assumptions_changed?
         perform_update
       else
         flash.now[:warning] = 'With assumptions changed, you will need to recomputes all properties in this market.<br> Are you sure you want to continue saving changes?'.html_safe
         render 'edit'
       end
     end
     
     
    
  end
  
  # def update
    # update! do
#       
      # collection_url
#       
    # end
    # if @market.save?
      # edit_resource_url(@market)
    # else
      # collection_url
    # end
     
    
    # if @market.assumption_changed?
      # edit_resource_url(@market)
    # else
      # update!
      # collection_url
    # end
    
    # puts "market rental_comp_query: #{@market.rental_comp_query}"
    # puts "market rental_comp_query changed?: #{@market.rental_comp_query_changed?}"
#     
    # rental_comp_query = @market.rental_comp_query
#     
    # update! do
      # puts "market rental_comp comparison: #{rental_comp_query} vs  #{@market.rental_comp_query}"
      # if rental_comp_query !=  @market.rental_comp_query
        # edit_resource_url(@market)
      # else 
        # # @market.save
        # collection_url
      # end
    # end
    # @market = Market.new(params[:market])
    # update!
    # if @market.assumption_changed?
      # puts "aaaa"
      # redirect_to "http://www.google.co.th"
      # # redirect_to edit_resource_url(:market => params[:market] )
    # else
      # redirect_to collection_url
    # end
  # end
  
  protected

    def collection
      @markets = Market.includes(:users).page(params[:page])
    end
    
    def perform_update
      if @market.save
        redirect_to url_for(:action => :index), :notice => 'Settings saved successfully!'
      else
        flash.now[:error] = 'Settings could not be saved, check errors!'
        render 'edit'
      end
    end

end

app/controllers/client/markets_controller.rb
class Client::MarketsController < Client::BaseController
  before_filter proc { load_market_and_assignment(:id) }
  acts_as_resource do
    actions :all, except: [:show]
  end
  
  def show
    if can? :create, Search
      redirect_to new_client_market_search_url(@market)
    elsif can? :create, Job
      redirect_to new_client_market_upload_url(@market)
    end
  end
  
  def update
    
     if params[:restore]
      @assignment.restore!
      redirect_to url_for(:action => :edit), :notice => 'Settings restored successfully from market default values!'
    else
      if @assignment.update_attributes(params[:market_assignment])
        redirect_to url_for(:action => :edit), :notice => 'Settings saved successfully!'
      else
        flash.now[:error] = 'Settings could not be saved, check errors!'
        render 'edit'
      end
    end
     # @market.assign_attributes(params[:market])
     # if params[:confirm]
       # perform_update
     # else       
       # if !@market.assumptions_changed?
         # perform_update
       # else
         # flash.now[:warning] = 'With assumptions changed, you will need to recomputes all properties in this market.<br> Are you sure you want to continue saving changes?'.html_safe
         # render 'edit'
       # end
     # end
     
     
    
  end
  
  # def update
    # update! do
#       
      # collection_url
#       
    # end
    # if @market.save?
      # edit_resource_url(@market)
    # else
      # collection_url
    # end
     
    
    # if @market.assumption_changed?
      # edit_resource_url(@market)
    # else
      # update!
      # collection_url
    # end
    
    # puts "market rental_comp_query: #{@market.rental_comp_query}"
    # puts "market rental_comp_query changed?: #{@market.rental_comp_query_changed?}"
#     
    # rental_comp_query = @market.rental_comp_query
#     
    # update! do
      # puts "market rental_comp comparison: #{rental_comp_query} vs  #{@market.rental_comp_query}"
      # if rental_comp_query !=  @market.rental_comp_query
        # edit_resource_url(@market)
      # else 
        # # @market.save
        # collection_url
      # end
    # end
    # @market = Market.new(params[:market])
    # update!
    # if @market.assumption_changed?
      # puts "aaaa"
      # redirect_to "http://www.google.co.th"
      # # redirect_to edit_resource_url(:market => params[:market] )
    # else
      # redirect_to collection_url
    # end
  # end
  
  protected

    def collection
      @markets = Market.includes(:users).page(params[:page])
    end
    
    def perform_update
      
      m  = @market.save
      Delayed::Worker.logger.debug "m: #{@market.errors.full_messages}"
      if m
        redirect_to url_for(:action => :index), :notice => 'Settings saved successfully fu!'
      else
        flash.now[:error] = 'Settings could not be saved, check errors!'
        render 'edit'
      end
    end

end

app/controllers/markets/base_controller.rb
class Markets::BaseController < ApplicationController
  before_filter :load_market_and_assignment

end

app/controllers/markets/uploads_controller.rb
class Markets::UploadsController < Markets::BaseController
  before_filter :prepare_job, only: [:new, :create]

  acts_as_resource(Job) do 
    defaults route_prefix: nil
    belongs_to :market
    custom_actions collection: [:template], resource: [:export,:comps_report]
  end
  
  def new
    session.delete(:selected_tab)
    new!
  end
  
  def index
    @reload = 30000
    index!
  end

  def destroy
    resource.delete
    redirect_to collection_url
  end

  def template
    download(:csv, 'template', Property.limit(0).to_csv(Property::IMPORT_FIELDS))
  end
  
  def activate_tab
    session[:selected_tab] =   params[:selected_tab]
    render :nothing => true
  end

  def show
    ids = (resource.info[:ids] || '').split(' ')
    @properties = @market.properties.joins_proforma.where(id: ids).page(params[:page]).order_by(sort_by, sort_asc)
  end

  def create
    @upload.assign_attributes(params[:market_upload_job])
    create!
  end
  
  def export
    ids = (resource.info[:ids] || '').split(' ')
    properties = @market.properties.joins_proforma.where(id: ids)
    download(:csv, 'report', properties.to_csv4(current_user.preferences.columns_results))
  end
  
  def comps_report
    ids = (resource.info[:ids] || '').split(' ')
    properties = @market.properties.joins_proforma.where(id: ids)
    download(:csv, 'comps_report', properties.to_comps_report(Property::COMPS_REPORT_FIELDS))
  end
  
  

  private

    def prepare_job 
      @upload = MarketUploadJob.new(market_id: @market.try(:id), user_id: current_user_id)
      @upload.overrides = Array.new(3, {}) if can?(:bulk, Job)
    end

    def collection
      @uploads = @market.uploads.where(user_id: current_user_id).page(params[:page]).desc(:run_at)
    end

end

app/controllers/markets_controller.rb
class MarketsController < ApplicationController
  before_filter proc { load_market_and_assignment(:id) }
  acts_as_resource

  def show
    if can? :create, Search
      redirect_to new_market_search_url(@market)
    elsif can? :create, Job
      redirect_to new_market_upload_url(@market)
    end
  end

  def update
    if params[:restore]
      @assignment.restore!
      redirect_to url_for(:action => :edit), :notice => 'Settings restored successfully from market default values!'
    else
      if @assignment.update_attributes(params[:market_assignment])
        redirect_to url_for(:action => :edit), :notice => 'Settings saved successfully!'
      else
        flash.now[:error] = 'Settings could not be saved, check errors!'
        render 'edit'
      end
    end
  end

end

app/views/layouts/markets/properties.html.haml
- @title = @property.format(:address) if member?

= content_for(:breadcrumbs) do
  =breadcrumb 'Markets'
  =breadcrumb @market.format(:fullname), market_url(@market)
  - if member?
    =breadcrumb 'Properties'
- if params[:action] == "saved"
  = content_for(:pagination) do
    .addrem_saved{:style => "float: right; width: 220px; height: 20px; margin-right: 10px; text-align: right"}
      = saved_page_select({ data: { market_id: @market.id, page: params[:page] } }, session[:per_page])
= content_for(:navigation) do
  - if member?
    - if can? :summary, @property
      =nav_item t(:summary), summary_resource_url
    - if can? :proforma, @property
      =nav_item t(:proforma), proforma_resource_url    
    - if can? :comps, @property
      %li.dropdown{:class => (:active if action_name.match(/comps_/)) }
        %a.dropdown-toggle{'data-toggle' => :dropdown, :href => '#'}
          =t(:comps)
          %b.caret
        %ul.dropdown-menu
          - if can? :comps_rental, @property
            =nav_item t(:rental), comps_rental_resource_url
          - if can? :comps_sale, @property
            =nav_item t(:sale), comps_sale_resource_url
          - if can? :comps_build, @property
            =nav_item t(:build), comps_build_resource_url
    - if can? :map, @property
      =nav_item t(:map), map_resource_url
    - if can? :mls, @property
      =nav_item t(:mls), @property.mls_url, target: :_blank
    
    %li.dropdown
      %a.dropdown-toggle{'data-toggle' => :dropdown, :href => '#'}
        ="Property Data"
        %b.caret
      %ul.dropdown-menu
        - if can? :tax, @property
          =nav_item t(:tax), @property.tax_url, target: :_blank
        - if can? :deed, @property
          =nav_item t(:deed), @property.deed_url, target: :_blank
        - if can? :zillow, @property
          =nav_item t(:zillow), @property.zillow_url, target: :_blank
        - if can? :pshark, @property
          =nav_item t(:pshark), @property.pshark_url, target: :_blank
     
    - if can? :comment, @property
      =nav_item "Contact & Notes", comment_resource_url
    - if can? :download, @property
      %li.dropdown
        %a.dropdown-toggle{'data-toggle' => :dropdown, :href => '#'}
          ="Evaluation"
          %b.caret
        %ul.dropdown-menu
          - if can? :level2, @property
            =nav_item t(:level2), level2_resource_url
          - if can? :level3, @property
            =nav_item t(:level3), level3_resource_url
    - if can? :edit, @property
      =nav_item t(:edit), edit_resource_url
    - if can? :raw, @property
      =nav_item t(:raw), raw_resource_url
  - elsif collection?
   
    - if current_user.admin? || current_user.role == 'analyst'
      =nav_item t(:results), saved_market_properties_url(params_without_action)
    - if current_user.admin? || current_user.role == 'analyst'
      %li.dropdown
        %a.dropdown-toggle{'data-toggle' => :dropdown, :href => '#'}
          =t(:download)
          %b.caret
        %ul.dropdown-menu
          - if current_user.admin? || current_user.role == 'analyst'
            =nav_item t(:excel), export_market_properties_url(params_without_action)
  
= content_for(:addrem_saved) do
  - if member? && MyProp.my_prop_exists(@property.id, current_user.id) 
    .addrem_saved{:style => "float: right; width: 200px; height: 20px; margin-right: 10px; text-align: right"}
      = link_to "Remove from My Props", {:controller => "properties", :action => "remove_saved", :referer => request.referer } 
  - elsif member?
    .addrem_saved{:style => "float: right; width: 200px; height: 20px; margin-right: 10px; text-align: right"}
      = link_to "Add to My Props", {:controller => "properties", :action => "add_saved", :referer => request.referer }  
    
= content_for(:content) do
  - if member?
    .row
      .span3
        =image_for(@property)
      .span3
        =definitions_for2(@property, :style => "margin-bottom: 0px" ) do |d|
          =d.rows :status, :category, :list_price 
          =d.row :list_price_psf, as: :money_w_two_decimal
          =d.row :sale_price, label: 'Sold Price' 
          =d.row :year_built
      .span3
        =definitions_for2(@property, :style => "margin-bottom: 0px") do |d|
          =d.rows :mls_number, :tax_id, :id, :legal_subdivision
          =d.row :subdivision_full, definition_class: 'Property', label: 'Subdivision'
          =d.row :avg_school_rating, label: 'Avg. School Rate'
          
      .span3
        =definitions_for2(@property, :style => "margin-bottom: 0px") do |d|
         
          =d.row :square_feet
          =d.rows :lot_square_feet, :beds, :bathrooms, :cdom, :dom
    .row
      = simple_form_for([@market, @property], url: edit_market_property_url, method: :post) do |f|
        .span3
          = f.hidden_field "market_id"
          = f.hidden_field "id"
        .span3
          - disabled_items = []
          - disabled_items =  User.all.map(&:id).reject! {|d| d == current_user.id  } if !current_user.admin? && !(current_user.role == "analyst")
          = prop_mul_rep(f, User.order("firstname , lastname").all.map{|s| [ [(s.firstname.nil? ? '':s.firstname),(s.lastname.nil? ? '': s.lastname)].join(' ').gsub(/^\s\s*/, '').gsub(/\s\s*$/, ''), s.id.to_s]},  (@property.rep ? @property.rep : "" ).split(",").each {|t| t.strip!}, disabled_items  )
          = flood_select(f, [["High","high"],["Moderate-Low","moderate-low"],["Undetermined","undetermined"]], @property.flood)    
        .span3
          - Property.assign_user_id(current_user.id)
          = prop_select(f, @property.market.property_tags.map{|s| [s.name, s.id.to_s]}, @property.user_assigned_tag.nil? ? nil : @property.user_assigned_tag.tag   )
          = near_commercial_select(f, [["Yes","1"],["No","0"]], (@property.near_commercial == true ?  "1" : (@property.near_commercial == false ? "0" : @property.near_commercial  ) )  )
        .span3
          = prop_user_update(f, @property.user_updated_at) 
          = prop_county(f, @property.county)
    %br
  =yield
  
  - if @market.id == 9 && !controller.action_name.to_sym.in?([:proforma,:comps_sale,:comps_rental,:comps_build,:comment,:edit])
    .blocktext
      .aleft
        = image_tag("fmls_logo.jpg")
      .span13{ :style => "float: left; width: 480px; margin-left: 10px" }= "Listing content provided by FMLS and deemed reliable but not guaranteed." 
      .fmls_bottom{:style => "clear:both; text-align: center;" }= "©2014 First Multiple Listing Service, Inc.​"
    %br
    %br  
= render :template => 'layouts/application'

app/views/layouts/markets/searches.html.haml
- @title = defined?(@search) ? @search.name || 'Search' : 'Saved Searches'

= content_for(:breadcrumbs) do
  =breadcrumb 'Markets'
  =breadcrumb @market.format(:fullname), market_url(@market)
  - if member? && @search.persisted?
    =breadcrumb 'Saved Searches', collection_url

- if params[:action] == "show"
  = content_for(:pagination) do
    .addrem_saved{:style => "float: right; width: 220px; height: 20px; margin-right: 10px; text-align: right"}
      = page_select({ data: { market_id: @market.id, search_id: params[:id]} }, session[:per_page])

= content_for(:navigation) do
  - if member?
    - if can? :show, @search
      =nav_item t(:results), resource_url(params_without_action)
    - if params[:action] == "show"
      - if can? :map, @search
        =nav_item t(:map), map_resource_url(params_without_action), target: :_blank
    - if params[:action] == "show"
      - if can? :add_my_prop, @search
        =nav_item t(:add_my_prop), "#", class: "add-my-prop", data: {app_root: ENV["RAILS_RELATIVE_URL_ROOT"], market_id: @market.id, search_id: params[:id]}
    - if params[:action] == "show"
      - if can? :add_label, @search
        %li.dropdown
          %a.dropdown-toggle{'data-toggle' => :dropdown, :href => '#'}
            =t(:add_label)
            %b.caret
          %ul.dropdown-menu

            - for tag in @property_tags
              =nav_item tag.name, "#", class: "add-label", data: {app_root: ENV["RAILS_RELATIVE_URL_ROOT"], market_id: @market.id, search_id: params[:id], tag_id: tag.id}
    - if params[:action] == "show"
      - if can? :download, @search
        %li.dropdown
          %a.dropdown-toggle{'data-toggle' => :dropdown, :href => '#'}
            =t(:download)
            %b.caret
          %ul.dropdown-menu
            - if can? :export, @search
              =nav_item t(:excel), export_resource_url(params_without_action)
    - if can?(:edit, @search)
      =nav_item t(:edit), edit_resource_url(@search.persisted? ? {} : params_without_action)

= content_for(:content) do
  - if member?
    .row
      .span12= @search.format(:config)
    %hr
  =yield
  


= render :template => 'layouts/application'

app/views/layouts/markets/uploads.html.haml
- @title = member? ? @upload.handler_hash.format(:source) : 'Add Property'

= content_for(:breadcrumbs) do
  =breadcrumb 'Markets'
  =breadcrumb @market.format(:fullname), market_url(@market)
    
= content_for(:navigation) do
  - if can?(:index, Job)
    =nav_item t(:history), collection_url
  - if member?
    - if can? :download, @upload
      %li.dropdown
        %a.dropdown-toggle{'data-toggle' => :dropdown, :href => '#'}
          =t(:download)
          %b.caret
        %ul.dropdown-menu
          - if can? :export, @upload
            =nav_item t(:excel), export_resource_url(params_without_action)  
          
  - else
    - if can?(:new, Job)
      =nav_item t(:new), new_resource_url
      
   
  
= content_for(:content) do
  - if member?
    .row
      .span3
        = definitions_for(@upload) do |d|
          - for attr in [:run_at, :user, :source]
            =d.row attr
      .span3
        = definitions_for(@upload) do |d|
          - for attr in [:started_at, :completed_at, :status]
            =d.row attr
      .span3
        = definitions_for(@upload) do |d|
          - for attr in [:results_count, :errors_count]
            =d.row attr

  =yield

= render :template => 'layouts/application'